framework:
  # TODO
  # default_locale: "%locale%"
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
