twig:
    default_path: '%kernel.project_dir%/templates'
    exception_controller: null
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        '%kernel.project_dir%/public': web
        '%kernel.project_dir%/src/SuplaBundle/Resources/views': Supla

when@test:
    twig:
        strict_variables: true
