services:
  mariadb:
    image: mariadb:11.7.2
    container_name: supla-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: php
      MYSQL_DATABASE: supla
      MYSQL_USER: supla
      MYSQL_PASSWORD: php
      TZ: Europe/Warsaw
    volumes:
      - supla_db_data:/var/lib/mysql

  timescaledb:
    image: timescale/timescaledb:2.20.1-pg17
    container_name: supla-tsdb
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - supla_tsdb_data:/var/lib/postgresql/data:z

  smtp_server:
    profiles: [dev]
    container_name: supla-smtp
    image: gessnerfl/fake-smtp-server:2.4.2
    ports:
      - "2500:8025"
      - "6245:8080"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  supla_db_data:
  supla_tsdb_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
