# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

     app.locale_listener:
        class: SuplaBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
                        
     form.type.channelfunction:
        class: SuplaBundle\Form\Type\ChannelFunctionType
        tags:
            - { name: form.type, alias: channelfunction }
        arguments:
             iodevice_manager: "@iodevice_manager"   
           
     supla_mailer:
         class: SuplaBundle\Mailer\SuplaMailer        
         arguments:
              router: "@router"
              templating: "@templating"
              mailer: "@mailer"
              mailer_from: '%mailer_from%'
              admin_email: '%admin_email%'
              supla_server: '%supla_server%'
                                         
     user_manager:
         class: SuplaBundle\Model\UserManager
         arguments:
              doctrine: "@doctrine" 
              encoder_factory: "@security.encoder_factory"
              accessid_manager: "@accessid_manager"
              location_manager: "@location_manager"
              scheduleManager: '@schedule_manager'
              
     oauth_user_provider:
         class: SuplaApiBundle\Provider\ApiUserProvider
         arguments:
              user_manager: "@api_manager" 
              
     accessid_manager:
         class: SuplaBundle\Model\AccessIdManager
         arguments:
              translator: "@translator"
              doctrine: "@doctrine" 
              security_token: "@security.token_storage"
              
     location_manager:
         class: SuplaBundle\Model\LocationManager
         arguments:
              translator: "@translator"
              doctrine: "@doctrine" 
              security_token: "@security.token_storage"
              
     iodevice_manager:
         class: SuplaBundle\Model\IODeviceManager
         arguments:
              translator: "@translator"
              doctrine: "@doctrine" 
              security_token: "@security.token_storage"
              template: "@templating"
              
     api_manager:
         class: SuplaApiBundle\Model\APIManager
         arguments:
              doctrine: "@doctrine" 
              encoder_factory: "@security.encoder_factory"
              container: "@service_container"
              
     schedule_manager:
         class: SuplaBundle\Model\Schedule\ScheduleManager
         arguments:
              doctrine: "@doctrine"
              ioDeviceManager: '@iodevice_manager'
              schedulePlanner: '@schedule_planner.composite'

     schedule_planner.composite:
         class: SuplaBundle\Model\Schedule\SchedulePlanners\CompositeSchedulePlanner
         arguments:
              -
                - '@schedule_planner.sunrise_sunset'
                - '@schedule_planner.cron'

     schedule_planner.cron:
         class: SuplaBundle\Model\Schedule\SchedulePlanners\CronExpressionSchedulePlanner

     schedule_planner.sunrise_sunset:
         class: SuplaBundle\Model\Schedule\SchedulePlanners\SunriseSunsetSchedulePlanner

     server_list:
         class: SuplaBundle\Supla\ServerList
         arguments: 
                 router: "@router"
                 user_manager: "@user_manager"
                 supla_server: '%supla_server%'
                 supla_server_list: '%supla_server_list%'
              
        
     authentication_handler:
        class: SuplaBundle\Handler\AuthHandler
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            router: "@router"
         
               
     validator.supla.channel:
        class: SuplaBundle\Validator\Constraints\ChannelValidator
        tags:
            - { name: validator.constraint_validator, alias: channel_validator }
        arguments:
             iodevice_manager: "@iodevice_manager"     
             
     validator.supla.usernameexists:
        class: SuplaBundle\Validator\Constraints\UsernameExistsValidator
        tags:
            - { name: validator.constraint_validator, alias: username_exists_validator }
        arguments:
             user_manager: "@user_manager"    
            

     twig.extension.io_device_attributes_to_string:
        class: SuplaBundle\Twig\IoDeviceAttributesToStringExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
            
     twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

     supla.event_listener.ajax_exception_handler:
        class: SuplaBundle\EventListener\AjaxExceptionHandler
        arguments:
          - '%kernel.debug%'
        tags:
          - { name: kernel.event_subscriber }


     supla.assets.versioning.webpack:
        class: SuplaBundle\Twig\WebpackAssetVersionStrategy
        arguments:
          - '%use_webpack_dev_server%'
          - '%kernel.root_dir%/webpack-hashes.php'
        public: false
