# very lazy migration to the new configuration
# http://symfony.com/doc/master/service_container/3.3-di-changes.html#upgrading-to-the-new-symfony-3-3-configuration
services:
  location_manager: '@SuplaBundle\Model\LocationManager'
  iodevice_manager: '@SuplaBundle\Model\IODeviceManager'
  accessid_manager: '@SuplaBundle\Model\AccessIdManager'
  api_manager: '@SuplaBundle\Model\APIManager'
  user_manager: '@SuplaBundle\Model\UserManager'
  supla_mailer: '@SuplaBundle\Mailer\SuplaMailer'
