imports:
  - { resource: services_legacy_aliases.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'

  SuplaBundle\EventListener\LocaleListener:
    arguments:
      - "%kernel.default_locale%"
    tags:
      - { name: kernel.event_subscriber }

  SuplaBundle\Handler\AuthHandler: ~

  SuplaBundle\Form\Type\ChannelFunctionType:
    tags:
      - { alias: channelfunction, name: form.type }

  SuplaApiBundle\Provider\ApiUserProvider: ~

  SuplaBundle\Model\:
    resource: '../../src/SuplaBundle/Model'

  SuplaBundle\Model\Schedule\SchedulePlanners\CompositeSchedulePlanner:
    $planners:
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\IntervalSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\SunriseSunsetSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\CronExpressionSchedulePlanner'

  SuplaApiBundle\Model\APIManager: ~

  SuplaBundle\Supla\:
    resource: '../../src/SuplaBundle/Supla'
  SuplaBundle\Supla\ServerList:
    $supla_server: "%supla_server%"
    $supla_server_list: "%supla_server_list%"

  SuplaBundle\Twig\WebpackAssetVersionStrategy:
    arguments:
      - "%use_webpack_dev_server%"
      - "%supla.webpack_hashes%"

  SuplaApiBundle\Provider\OAuthStorageWithLegacyPasswordSupport:
    $userProvider: '@SuplaApiBundle\Provider\ApiUserProvider'

  SuplaBundle\EventListener\AjaxExceptionHandler:
    arguments:
      - "%kernel.debug%"
    tags:
      - { name: kernel.event_subscriber }

  SuplaBundle\EventListener\LegacyPasswordMigrationListener:
    tags:
      - { event: security.interactive_login, name: kernel.event_listener }

  SuplaBundle\Mailer\SuplaMailer:
    $mailer_from: "%mailer_from%"
    $email_admin: "%admin_email%"
    $supla_server: "%supla_server%"

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl

  SuplaBundle\Twig\IoDeviceAttributesToStringExtension: ~

  SuplaBundle\Validator\Constraints\ChannelValidator:
    tags:
      - { alias: channel_validator, name: validator.constraint_validator }

  SuplaBundle\Validator\Constraints\UsernameExistsValidator:
    tags:
      - { alias: username_exists_validator, name: validator.constraint_validator }
